name: Create SharePoint Site

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 9 * * *' # Runs daily at 09:00 UTC

jobs:
  create-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests msal

      - name: Create SharePoint Site via Graph
        env:
          CLIENT_ID: ${{ secrets.APP_ID }}
          CLIENT_SECRET: ${{ secrets.APP_SECRET }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
        run: |
          python create_site.py
